language: elixir
elixir:
- 1.8.2
otp_release:
  - '21.2.5'
addons:
  postgresql: '9.4'
services:
- postgresql: '9.4'
env:
- MIX_ENV=test
before_script:
- cp config/travis.exs config/test.exs
- mix do ecto.create, ecto.migrate
script:
- mix test
deploy:
  provider: heroku
  app:
  buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
